apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: helloworld-go
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'helloworld-go:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/emilevauge/go-helloworld'
    type: Git
  strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 's2i-golang:latest'
          namespace: myproject
      type: Source
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 38ccfe1c7270109f
      type: Generic
    - github:
        secret: 259d9ff7a282e8ff
      type: GitHub
status:
  lastVersion: 0
